### PR TITLE
Create standardize_coordinates.R

### PR DESCRIPTION
**Pull request by larsmaurath**
Code to standardize location columns to a 105m x 68m pitch size.

### CODE REVIEW

**Comment by RobWHickman** [comment]
whew finally getting round to this this weekend- 

A to-do list that I'll get around to but if you want to do any of course is appreciated!

1. Refactor standardised coords into existing spadl conversion script
2. Refactor numbers into params file and source from there
3. Write simple tests for expected behaviour of conversion - e.g. does x for provider y convert to z every time
4. Write collision tests with real life data - e.g. does this lead to penalties for events we think are outside of the box

**Comment by larsmaurath** [comment]
Hey Rob, thanks for the response! Was actually also moving apartments (sorry for the delay). Have definitely thought about 3) & 4) and am happy to implement. Already saw that you have a testthat file, so will try so using that framework. 

Do you have an example of how you want 2) implemented (how to store, ...) Happy to follow your guidance on this.

You probably know best for 1)

**Comment by RobWHickman** [comment]
afaik 2 is working, maybe cluttering the /data/ with single variables but I'll let that happen for now.

Apologies again Im being horrendously slow with this! will do one more effort tonight and pull in so anything not done can be sorted on a later branch!

**Comment by larsmaurath** [comment]
No problem at all! Will look next at 3 & 4 and will submit another pull request with appropriate tests. Next big feature to add from my side would be a plotting function that plots events from a standardized data set. Pretty standard but would appreciate your feedback on its features when the time comes.

**Comment by larsmaurath** [comment]
Tests already flagged an issue. Will submit both the fix and the initial testing together once I have it set up.

**Pull request merged**
